[versions]
minecraft = "1.19.4"
quilt_mappings = "1.19.4+build.10"
fabric_loader = "0.14.21"
fabric_api = "0.83.0+1.19.4"
modmenu = "6.2.3"
origins = "v1.9.0"
mixinextras = "0.0.11"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
quilt_mappings = { module = "org.quiltmc:quilt-mappings", version.ref = "quilt_mappings" }

fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
origins = { module = "com.github.apace100:origins-fabric", version.ref = "origins" }
mixinextras = { module = "com.github.LlamaLad7:MixinExtras", version.ref = "mixinextras" }

# If you have multiple similar dependencies, you can declare a dependency bundle and reference it on the build script with "libs.bundles.example".
[bundles]

[plugins]
